### ISSUE TITLE
Symbol Lookup Error

### ISSUE THREAD

**Issue by juldavid** [JuliaPolyhedra/CDDLib.jl#26]
Hello, i'm having a problem to compile CDDLib in Julia.
Apparently, the compiler is unable to link libcddgmp.so to the libgmp

I get the following message when I try to do `using CDDLib`:
```
symbol lookup error: /usr/local/lib/libcddgmp.so: undefined symbol: __gmpq_init
```
libgmp-dev is installed (i tried to remove it and reinstall it)
I also tried to add -lgmp in the build.jl but it does not work either.

Any idea?

**Comment by juldavid** [comment]
Actually, I solved the problem by exporting the path of libgmp.so into LD_PRELOAD

**Comment by blegat** [comment]
Which distribution are you using ?

**Comment by easalgadov** [comment]
I'm facing the same problem, could you please elaborate more on how you solve it?

**Comment by easalgadov** [comment]
@blegat  no, it is in the ``.../julia-d386e40c17/lib/julia``. My OS is Ubuntu 18.04

**Comment by blegat** [comment]
Could you try doing something like
```
$ LD_PRELOAD=julia-d386e40c17/lib/julia:$LD_PRELOAD julia -e 'Pkg.build("CDDLib")'
```
as suggested by @juldavid ?

**Comment by trigaut** [comment]
I had to put this to my .bashrc:
`export LD_PRELOAD=yourpath/libgmp.so:$LD_PRELOAD`

I had to change LD_PRELOAD not only to build CDDLib.jl but everytime I use CDDLib.jl.

**Comment by odow** [comment]
This should be closed as out-dated. We know ship `cddlib_jll` which should fix these issues.
