### ISSUE TITLE
Switch to BinaryBuilder

### ISSUE THREAD

**Issue by saschatimme** [JuliaPolyhedra/CDDLib.jl#27]
Hey,

I tried to move this over to the new [BinaryBuilder.jl](https://github.com/JuliaPackaging/BinaryBuilder.jl) but unfortunately failed somewhat miserably due to my restricted C / Linking skills.

I setup a repository with the build script and a travis config at https://github.com/saschatimme/CDDLibBuilder. [Here](https://travis-ci.org/saschatimme/CDDLibBuilder/jobs/398561690) is the log of the failed build. Unfortunately I currently do not have access to a linux machine with admin rights so I cannot locally debug this issue :(

Is there maybe something obvious I missed?

**Comment by blegat** [comment]
Thanks ! It would be very nice to switch to BinaryBuilder!
Maybe
https://github.com/JuliaPolyhedra/CDDLib.jl/blob/c5c3633dce0bf4eccdccf55cd42aeda0742a8ac1/.travis.yml#L10
is missing ?

**Comment by saschatimme** [comment]
Things are a little bit more complicated, BinaryBuilder boots something like a docker image for each build target and so you have to install everything in the respective image for each build.

I managed to get a build working for Linux and MacOS but although things run through there is a warning
```
Warning: Linked library libgmp.so.10 could not be resolved and could not be auto-mapped
```
which doesn't make me too confident that everything is properly working.

Also on Windows (mingw32) things did not work related to some GMP problem (I also saw in the existing build script that windows needed some extra love).

**Comment by blegat** [comment]
This is now done :)
