### ISSUE TITLE
CDDSolver(exact=true)

### ISSUE THREAD

**Issue by oyamad** [JuliaPolyhedra/CDDLib.jl#31]
Consider the example in https://mathprogbasejl.readthedocs.io/en/latest/linprog.html:

```jl
using CDDLib
using MathProgBase
lp_solver = CDDSolver(exact=true)
```

```jl
sol = linprog([-1, 0], [2  1], '<', 3//2, lp_solver)
sol.objval
```

The value is `-3//4`.

Now divide both sides of the constraint by `3`:

```jl
sol = linprog([-1, 0], [2//3  1//3], '<', 1//2, lp_solver)
sol.objval
```

The outcome is `-4503599627370496//6004799503160661`.

If we divide by a multiple of `2`:

```jl
d = 2^20
sol = linprog([-1, 0], [2//d  1//d], '<', 3//(2*d), lp_solver)
sol.objval
```

then the outcome is exactly `-3//4`.

Is this a feature of `cdd`?

**Comment by blegat** [comment]
The problem is unbounded and the result is the unbounded ray ? In that case, the ray can be scaled by any value hence any negative number is a possible output

**Comment by oyamad** [comment]
If it is the case that omitting the `lb` means nonnegativity constraint, then this problem is bounded, as expressed in the page linked above:

min -x s.t. 2x + y <= 1.5, x, y >= 0.

The optimal solution is (x, y) = (1.5/2, 0) and the optimal value is -1.5/2 = -0.75. The first and third cases in my initial post output the exact solution.

**Comment by blegat** [comment]
Then this looks like a bug in CDD :/

**Comment by oyamad** [comment]
I guess I have spotted the "bug".

Call `buildlp`:

```jl
A = [2//3 1//3]
sense = '<'
b = 1//2
c = [-1//1, 0]
lp_solver = CDDSolver(exact=true)
m = buildlp(c, A, sense, b, lp_solver)
```

`m` is a [`PolyhedraToLPQPBridge`](https://github.com/JuliaPolyhedra/Polyhedra.jl/blob/fc5a01b1df9136457342c269ae1aea50d1a6a14d/src/polyhedra_to_lpqp.jl#L6-L17), where the entries are converted to `Float64`. In fact:

```jl
m.A
```

```
1×2 SparseArrays.SparseMatrixCSC{Float64,Int64} with 2 stored entries:
  [1, 1]  =  0.666667
  [1, 2]  =  0.333333
```

`Rational` should be kept in `PolyhedraToLPQPBridge`.
