### ISSUE TITLE
Incompatible with newest JuMP release

### ISSUE THREAD

**Issue by schillic** [JuliaPolyhedra/CDDLib.jl#48]
https://github.com/JuliaPolyhedra/CDDLib.jl/blob/3d86b4ce39db94c8b1e246c9ee9bb748fa8223e4/Project.toml#L17

Is it on purpose that newer versions are not allowed? The same holds for `Polyhedra.jl`.

**Comment by blegat** [comment]
For Polyhedra yes but for CDDLib it seems we could remove the JuMP dependency.

**Comment by blegat** [comment]
In fact we need the JuMP dependency for `with_optimizer`. It is bumped by https://github.com/JuliaPolyhedra/CDDLib.jl/commit/eb4d386ae573e401713f9c5254c6035f2816e540
