### ISSUE TITLE
Broken build on Windows and julia 1.4.1

### ISSUE THREAD

**Issue by ueliwechsler** [JuliaPolyhedra/CDDLib.jl#60]
Thanks for your great work!

I switched from `Julia 1.3.1` to `Julia 1.4.1` and wanted to build `CDDLib` on my Windows machine with `Julia 1.4.1` (see version info below) and I got the following error.  The build works on `Julia 1.3.1`.
```julia
(@v1.4) pkg> build CDDLib
ERROR: A dependency was named twice in target `test`
```
Not sure what to do with this error message, maybe you can help me out.
```julia
julia> versioninfo()
Julia Version 1.4.1
Commit 381693d3df* (2020-04-14 17:20 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-8.0.1 (ORCJIT, skylake)
```

**Comment by schillic** [comment]
There was such an error in #56 but that got fixed in v0.6.1. What version of `CDDLib` do you have (`]status`)?

**Comment by ueliwechsler** [comment]
Thanks!  I was on` CDDLib v0.5.3`. `LazySets@1.35`was holding it back, my bad, I switched to `LazySets#master` and now it works.

**Comment by schillic** [comment]
For the record, the new version of `LazySets` (v1.36.0) supports the latest version of `CDDLib` (v0.6.1).
