### ISSUE TITLE
Error in test.jl 

### ISSUE THREAD

**Issue by IlliaKovalenko94** [JuliaPolyhedra/CDDLib.jl#89]
Hello,

When I run **test.jl** in Jupyter, it return the following error:

MethodError: no method matching HRepresentation(::Matrix{Int64}, ::Vector{Int64})

Stacktrace:
 [1] extremepoints(A::Matrix{Int64}, b::Vector{Int64})
   @ Main .\In[9]:6
 [2] top-level scope
   @ In[9]:15

I need to find the extreme points of the convex hull of Ax<=b linear system where A is a [310x300] matrix. Is this problem solvable using cddlib? Any assistance with this would be highly appreciated  

![image](https://github.com/JuliaPolyhedra/CDDLib.jl/assets/140950244/21bb39d7-9d00-404e-bdba-e3883aa6c6c1)

**Comment by blegat** [comment]
This is an old syntax from a previous release I think, try `hrep(A, b)` instead. See https://juliapolyhedra.github.io/Polyhedra.jl/stable/representation/#Representation
